# This is not a config for a real Atlantis instance.
# I use Atlantis in production and I find it cool (except for the drift detection).
# So, here I provide an example configuration for an imaginary Atlantis instance that is used
# to run CI (plan) and CD (apply) for the team states.
---
version: 3
automerge: true # some people don't like it, but I prefer 1 change per 1 PR approach
autodiscover:
  mode: auto
  ignore_paths:
    - modules/
delete_source_branch_on_merge: true
parallel_plan: true # because we have multiple teams' states in the same repo
parallel_apply: true # same as above
# Default project config would live in the server-side Atlantis config
# projects:
# This workflow is only an illustration, if we use server-side project config,
# we need to configure the workflows there as well.
# Server-side config is preferable, because then the Platform team can control CICD for IC
workflows:
  custom:
    plan:
      - init
      - plan:
          extra_args: ["-lock", "false", "-var-file", "team.tfvars"]
    apply:
      - apply:
          extra_args: ["-var-file", "team.tfvars"]
    import:
      - init
      - import:
          extra_args: ["-var-file", "team.tfvars"]
